/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },

        // figma colours
        "washed-blue/washed-blue-50": "#e6f0ff",
        "washed-blue/washed-blue-100": "#b2d1ff",
        "washed-blue/washed-blue-200": "#8cbaff",
        "washed-blue/washed-blue-300": "#589bff",
        "washed-blue/washed-blue-400": "#3787ff",
        "washed-blue/washed-blue-500": "#0569ff",
        "washed-blue/washed-blue-600": "#0560e8",
        "washed-blue/washed-blue-700": "#044bb5",
        "washed-blue/washed-blue-800": "#033a8c",
        "washed-blue/washed-blue-900": "#022c6b",
        "washed-purple/washed-purple-50": "#f8f7ff",
        "washed-purple/washed-purple-100": "#e8e7ff",
        "washed-purple/washed-purple-200": "#dddcff",
        "washed-purple/washed-purple-300": "#cecbff",
        "washed-purple/washed-purple-400": "#c5c1ff",
        "washed-purple/washed-purple-500": "#b6b2ff",
        "washed-purple/washed-purple-600": "#a6a2e8",
        "washed-purple/washed-purple-700": "#817eb5",
        "washed-purple/washed-purple-800": "#64628c",
        "washed-purple/washed-purple-900": "#4c4b6b",
        "brand/washedPurple": "#b5b2ff",
        "brand/washedBlue": "#68b9ff",
        "brand/primaryPurple": "#7000ff",
        "brand/primaryBlue": "#0469ff",
        "brand/dark": "#030014",
        "Primary-blue/primary-blue-50": "#e6f0ff",
        "Primary-blue/primary-blue-100": "#b2d1ff",
        "Primary-blue/primary-blue-200": "#8cbaff",
        "Primary-blue/primary-blue-300": "#589bff",
        "Primary-blue/primary-blue-400": "#3787ff",
        "Primary-blue/primary-blue-500": "#0569ff",
        "Primary-blue/primary-blue-600": "#0560e8",
        "Primary-blue/primary-blue-700": "#044bb5",
        "Primary-blue/primary-blue-800": "#033a8c",
        "Primary-blue/primary-blue-900": "#022c6b",
        "Primary-Purple/primary-purple-50": "#f1e6ff",
        "Primary-Purple/primary-purple-100": "#d3b0ff",
        "Primary-Purple/primary-purple-200": "#bd8aff",
        "Primary-Purple/primary-purple-300": "#9f54ff",
        "Primary-Purple/primary-purple-400": "#8d33ff",
        "Primary-Purple/primary-purple-500": "#7000ff",
        "Primary-Purple/primary-purple-600": "#6600e8",
        "Primary-Purple/primary-purple-700": "#5000b5",
        "Primary-Purple/primary-purple-800": "#3e008c",
        "Primary-Purple/primary-purple-900": "#2f006b",
        "dark/dark-1": "#ffffff",
        "dark/dark-2": "#fcfcfd",
        "dark/dark-3": "#f5f5f6",
        "dark/dark-4": "#f0f0f1",
        "dark/dark-5": "#d9d9dc",
        "dark/dark-6": "#c0bfc4",
        "dark/dark-7": "#8d8c95",
        "dark/dark-8": "#5b5966",
        "dark/dark-9": "#464553",
        "dark/dark-10": "#282637",
        "dark/dark-11": "#201f30",
        "dark/dark-12": "#161427",
        "dark/dark-13": "#020014"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}